src/Entity/User.php
<?php
// src/App/Entity/User.php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
* @ORM\Table(name="app_users")
* @ORM\Entity(repositoryClass="App\Repository\UserRepository")
*/
class User implements UserInterface, \Serializable
{
/**
* @ORM\Column(type="integer")
* @ORM\Id
* @ORM\GeneratedValue(strategy="AUTO")
*/
private $id;

/**
* @ORM\Column(type="string", length=25, unique=true)
* @Assert\NotBlank(message="vul gebruikersnaam in")
*/
private $username;

/**
* @ORM\Column(type="string", length=255)
*/
private $password;

/**
* @ORM\Column(type="string", length=60, unique=false)
 *  @Assert\Email(
 *    message = "The email '{{ value }}' is geen geldig email adres")
 * @Assert\NotBlank(message="vul emailadres in")
*/
private $email;

/**
 * @Assert\Length(max=4096)
 * @Assert\NotBlank(message="vul wachtwoord in")
 */
private $plainPassword;

/**
 * @ORM\Column(type="json_array")
 */
private $roles = array();

/**
 * @ORM\Column(type="string", length=10)
 * @Assert\NotBlank(message="vul voorletters in")
 */
private $voorletters;

/**
 * @ORM\Column(type="string", length=10, nullable=true)
 */
private $tussenvoegsel;

/**
 * @ORM\Column(type="string", length=25)
 * @Assert\NotBlank(message="vul achternaam in")
 */
private $achternaam;

/**
 * @ORM\Column(type="string", length=25)
 * @Assert\NotBlank(message="vul adres in")
 *
 */
private $adres;

/**
 * @ORM\Column(type="string", length=7)
 * @Assert\NotBlank(message="vul postcode in")
 */
private $postcode;

/**
 * @ORM\Column(type="string", length=20)
 * @Assert\NotBlank(message="vul woonplaats in")
 */
private $woonplaats;
/**
 * @ORM\Column(type="string", length=15)
 *  @Assert\NotBlank(message="vul telfoonnummer in")
 */
private $telefoon;


public function getId()
{
    return $this->id;
}

function getNaam()
{
    return $this->voorletters." ".$this->tussenvoegsel." ".$this->achternaam;
}
/**
 * @return mixed
 */
public function getVoorletters()
{
    return $this->voorletters;
}

/**
 * @param mixed $voorletters
 */
public function setVoorletters($voorletters)
{
    $this->voorletters = $voorletters;
}

/**
 * @return mixed
 */
public function getTussenvoegsel()
{
    return $this->tussenvoegsel;
}

/**
 * @param mixed $tussenvoegsel
 */
public function setTussenvoegsel($tussenvoegsel)
{
    $this->tussenvoegsel = $tussenvoegsel;
}

/**
 * @return mixed
 */
public function getAchternaam()
{
    return $this->achternaam;
}

/**
 * @param mixed $achternaam
 */
public function setAchternaam($achternaam)
{
    $this->achternaam = $achternaam;
}

/**
 * @return mixed
 */
public function getAdres()
{
    return $this->adres;
}

/**
 * @param mixed $adres
 */
public function setAdres($adres)
{
    $this->adres = $adres;
}

/**
 * @return mixed
 */
public function getPostcode()
{
    return $this->postcode;
}

/**
 * @param mixed $postcode
 */
public function setPostcode($postcode)
{
    $this->postcode = $postcode;
}

/**
 * @return mixed
 */
public function getWoonplaats()
{
    return $this->woonplaats;
}

/**
 * @param mixed $woonplaats
 */
public function setWoonplaats($woonplaats)
{
    $this->woonplaats = $woonplaats;
}

/**
 * @return mixed
 */
public function getTelefoon()
{
    return $this->telefoon;
}

/**
 * @param mixed $telefoon
 */
public function setTelefoon($telefoon)
{
    $this->telefoon = $telefoon;
}


/**
 * Many Users have Many Activities.
 * @ORM\ManyToMany(targetEntity="Activiteit", inversedBy="users")
 * @ORM\JoinTable(name="deelnames")
 */
private $activiteiten;

public function __construct()
{
    $this->activiteiten = new \Doctrine\Common\Collections\ArrayCollection();
    $this->isActive = true;
}

public function addActiviteit(Activiteit $a)
{
    if ($this->activiteiten->contains($a)) {

        return;
    }

    $this->activiteiten->add($a);

}

public function removeActiviteit(Activiteit $a)
{
    if (!$this->activiteiten->contains($a)) {
        return;
    }
    $this->activiteiten->removeElement($a);
}
public function getEmail()
{
    return $this->email;
}

public function setEmail($email)
{
    $this->email = $email;
}

public function getUsername()
{
    return $this->username;
}

public function setUsername($username)
{
    $this->username = $username;
}

public function getPassword()
{
    return $this->password;
}

public function setPassword($password)
{
    $this->password = $password;
}

public function getPlainPassword()
{
    return $this->plainPassword;
}

public function setPlainPassword($password)
{
    $this->plainPassword = $password;
}

public function getSalt()
{
    // you *may* need a real salt depending on your encoder
    // see section on salt below
    return null;
}

public function getRoles()
{
    $roles = $this->roles;
    //$roles[] = 'ROLE_USER';

    return array_unique($roles);
}
public function setRoles(array $roles)
{
    $this->roles = $roles;

    // allows for chaining
    return $this;
}

public function eraseCredentials()
{
    $this->plainPassword = null;
}

/** @see \Serializable::serialize() */
public function serialize()
{
return serialize(array(
$this->id,
$this->username,
$this->password,
// see section on salt below
// $this->salt,
));
}

/** @see \Serializable::unserialize() */
public function unserialize($serialized)
{
list (
$this->id,
$this->username,
$this->password,
// see section on salt below
// $this->salt
) = unserialize($serialized);
}
}

src/Controller/DeelnemerController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class DeelnemerController extends Controller
{
    /**
     * @Route("/user/activiteiten", name="activiteiten")
     */
    public function activiteitenAction()
    {
        $usr= $this->get('security.token_storage')->getToken()->getUser();

        $beschikbareActiviteiten=$this->getDoctrine()
            ->getRepository('App:Activiteit')
        ->getBeschikbareActiviteiten($usr->getId());

        $ingeschrevenActiviteiten=$this->getDoctrine()
            ->getRepository('App:Activiteit')
            ->getIngeschrevenActiviteiten($usr->getId());

        $totaal=$this->getDoctrine()
            ->getRepository('App:Activiteit')
            ->getTotaal($ingeschrevenActiviteiten);


        return $this->render('deelnemer/activiteiten.html.twig', [
                'beschikbare_activiteiten'=>$beschikbareActiviteiten,
                'ingeschreven_activiteiten'=>$ingeschrevenActiviteiten,
                'totaal'=>$totaal,
        ]);
    }

    /**
     * @Route("/user/inschrijven/{id}", name="inschrijven")
     */
    public function inschrijvenActiviteitAction($id)
    {

        $activiteit = $this->getDoctrine()
            ->getRepository('App:Activiteit')
            ->find($id);
        $usr= $this->get('security.token_storage')->getToken()->getUser();
        $usr->addActiviteit($activiteit);

        $em = $this->getDoctrine()->getManager();
        $em->persist($usr);
        $em->flush();

        return $this->redirectToRoute('activiteiten');
    }

    /**
     * @Route("/user/uitschrijven/{id}", name="uitschrijven")
     */
    public function uitschrijvenActiviteitAction($id)
    {
        $activiteit = $this->getDoctrine()
            ->getRepository('App:Activiteit')
            ->find($id);
        $usr= $this->get('security.token_storage')->getToken()->getUser();
        $usr->removeActiviteit($activiteit);
        $em = $this->getDoctrine()->getManager();
        $em->persist($usr);
        $em->flush();
        return $this->redirectToRoute('activiteiten');
    }

    /**
     * @Route("/user/mijnProfiel", name="mijnProfiel")
     */
    public function mijnProfiel(Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = $this->get('security.token_storage')->getToken()->getUser();

        $form = $this->createForm(UserType::class, $user);
        $form->add('save', SubmitType::class, array('label'=>"aanpassen"));

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $user = $entityManager->find(User::class, $this->getUser()->getId());
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash(
                'notice',
                'gegevens aangepast!'
            );
            return $this->redirectToRoute('activiteiten');
        }

        return $this->render('deelnemer/mijnProfiel.html.twig',array('form'=>$form->createView()));
    }


}

templates/deelnemer/activiteiten.html.twig
{% extends 'deelnemer.html.twig' %}
{% block menu %}
    <li><a href="{{ path('activiteiten') }}">home</a></li>
    <li><a href="{{ path('mijnProfiel') }}">Mijn Profiel</a></li>


{% endblock %}


{% block content %}
<section >
    <table class="table" style="table-layout: fixed" >
        <caption>
            Dit zijn alle beschikbare activiteiten
        </caption>
        <thead>
        <tr>
            <td>datum</td>
            <td>tijd</td>
            <td>soort activiteit</td>
            <td>prijs</td>
            <td>schrijf in</td>
        </tr>
        </thead>
        <tbody>
        {% for activiteit in beschikbare_activiteiten %}
        <tr>
            <td>
                {{ activiteit.datum|date("d-m-Y")}}
            </td>
            <td>
                {{ activiteit.tijd|date("H:i")}}
            </td>

            <td>
                {{ activiteit.soort.naam}}
            </td>
            <td>
                &euro;{{ activiteit.soort.prijs|number_format(2,',','.')}}
            </td>
            <td title="schrijf in voor activiteit">


                <a href="{{ path('inschrijven', {'id':activiteit.id}) }}" >
                    <span class="glyphicon glyphicon-plus" style="color:red"></span>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <table class="table" style="table-layout: fixed">
        <caption>
            Dit zijn de door jou ingeschreven activiteiten
        </caption>
        <thead>
        <tr>
            <td>datum</td>
            <td>tijd</td>
            <td>soort activiteit</td>
            <td>prijs</td>
            <td>schrijf uit</td>
        </tr>
        </thead>
        <tbody>
        {% for activiteit in ingeschreven_activiteiten %}
            <tr>
                <td>
                    {{ activiteit.datum|date("d-m-Y")}}
                </td>
                <td>
                    {{ activiteit.tijd|date("H:i")}}
                </td>

                <td>
                    {{ activiteit.soort.naam}}
                </td>
                <td>
                    &euro;{{ activiteit.soort.prijs|number_format(2,',','.')}}
                </td>
                <td title="schrijf in voor activiteit">
                    <a href="{{ path('uitschrijven', {'id':activiteit.id}) }}" >
                        <span class="glyphicon glyphicon-minus" style="color:red"></span>
                    </a>
                </td>

            </tr>
        {% endfor %}
        <tr>
            <td>
            </td>
            <td>
            </td>
            <td>
                Totaal prijs:
            </td>
            <td>
                &euro;{{totaal|number_format(2,',','.')}}

            </td>
            <td>
            </td>
        </tr>

        </tbody>
    </table>
</section>


{% endblock %}

templates/deelnemer/mijnProfiel.html.twig
{% extends 'deelnemer.html.twig' %}
{% block menu %}
    <li><a href="{{ path('activiteiten') }}">home</a></li>
    <li><a href="{{ path('mijnProfiel') }}">Mijn Profiel</a></li>


{% endblock %}
{% block content %}

    <h3>Mijn profiel</h3>

    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}


{% endblock %}